# whitelist the following branches for building
branches:
  only:
    - master
    - dev

env:
  global:
    - TEST_DIR=tmp/
    - REQUIREMENTS=build_tools/requirements.txt

dist: xenial
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    # add more combinations here as per requirement
    - env: PYTHON_VERSION="3.6" TF_VERSION="1.9"
    - env: PYTHON_VERSION="3.6" TF_VERSION="1.15"
    - env: PYTHON_VERSION="3.7" TF_VERSION="2.1"

install:
  # Install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH

  # Configure conda
  - conda config --set always_yes true
  - conda update --quiet conda

  # create the testing environment
  - conda create --name testenv python="$PYTHON_VERSION" tensorflow="$TF_VERSION"
  - source activate testenv
  - pip install cython
  - pip install -r "$REQUIREMENTS"

  # for test pypi add dependency installs manually
  - python setup.py bdist_wheel
  - pip install --pre --no-index --no-deps --find-links dist/ sktime-dl

  # now need to install keras-contrib for tf.keras instead of standalone keras
  # not needed for the tf_version 2.1 env, but does not hurt either. investigate
  # conditional installation
  - git clone https://www.github.com/keras-team/keras-contrib.git
  - cd keras-contrib
  - python convert_to_tf_keras.py
  - USE_TF_KERAS=1 python setup.py install
  - cd ..

script:
  - source build_tools/test.sh

after_success:
  - coveralls



